# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appellation', models.CharField(blank=True, help_text="L'appellation du vin", max_length=255, verbose_name='appellation')),
                ('area', models.CharField(blank=True, help_text='La r\xe9gion du vin', max_length=255)),
                ('cuvee', models.CharField(blank=True, help_text='La cuv\xe9e associ\xe9e au vin', max_length=255)),
                ('name', models.CharField(blank=True, help_text='Le nom du vin', max_length=255)),
                ('wine_color', models.CharField(choices=[('RO', 'Rouge'), ('BL', 'Blanc'), ('RO', 'Ros\xe9'), ('JA', 'Jaune'), ('NC', 'Non pr\xe9cis\xe9'), ('LI', 'Vin liquoreux')], help_text='La couleur du vin', max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Le mill\xe9sime du vin', null=True)),
            ],
        ),
    ]
